### ISSUE TITLE
bin/tree-tagger missing after runing the treetagger install script

### ISSUE THREAD

**Issue by JoWohlen** [PhilipEHausner/python_heideltime#1]
When I run the installation script the heideltime is not installed proper. The `tree-tagger` file is missing in `/bin`. The `/bin` folder is empty.
When running the example I got the following error:
![Untitled](https://user-images.githubusercontent.com/44275743/144764188-088b3941-8370-4789-8207-2f5d45f38020.png)
I could fix this by downloading the `Tree-Tagger` manually from https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/ after which i extracted the downloaded `/bin` into the empty `/bin` created by the installation script.

**Comment by dennlinger** [comment]
Hi @JoWohlen ,
thanks for the issue report (and sorry for not getting back earlier, somehow notifications were disabled for me)!
I independently figured out the same issue, but it should be fixed now with 2d7129a7e3fcd6105d5b9a1cb09c02115491f9a0.
In particular, they had a version bump in the tagger, which caused the old URL to no longer work.

FWIW, I think it would make sense to stick to a static version in our dependency tree, if only for the sake of consistency of its behavior.
I'll close this issue for now, but let me know if you have any further problems like this.

Best,
Dennis
